ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [org.athletica.crm.ApplicationKt.module]
    }
}

database {
    url = "jdbc:postgresql://127.0.0.1:5432/athletica"
    url = ${?POSTGRES_URL}
    user = "athletica"
    user = ${?POSTGRES_USER}
    password = "secret"
    password = ${?POSTGRES_PASSWORD}
}

jwt {
    secret = "dev-jwt-secret"
    secret = ${?JWT_SECRET}
    accessTokenTtlMinutes = 15
    refreshTokenTtlDays = 30
}

minio {
    endpoint = "http://localhost:9000"
    endpoint = ${?MINIO_ENDPOINT}
    accessKey = "minio_access_key"
    accessKey = ${?MINIO_ACCESS_KEY}
    secretKey = "minio_secret_key"
    secretKey = ${?MINIO_SECRET_KEY}
    bucket = "athletica-crm"
    bucket = ${?MINIO_BUCKET}
}

smtp {
    host = "smtp.go1.unisender.ru"
    host = ${?SMTP_HOST}
    port = 587
    username = "dev@localhost"
    username = ${?SMTP_USERNAME}
    password = "dev"
    password = ${?SMTP_PASSWORD}
    fromAddress = "robot@tronline.ru"
    fromAddress = ${?SMTP_FROM_ADDRESS}
    fromName = "AthleticaCRM"
}
