ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [org.athletica.crm.ApplicationKt.module]
    }
}

database {
    url = ${POSTGRES_URL}
    user = ${POSTGRES_USER}
    password = ${POSTGRES_PASSWORD}
}

jwt {
    secret = ${?JWT_SECRET}
    accessTokenTtlMinutes = 15
    refreshTokenTtlDays = 30
}

cors {
    allowedHosts = "localhost:8081"
    allowedHosts = ${?CORS_ALLOWED_HOSTS}
}

minio {
    endpoint = "http://localhost:9000"
    endpoint = ${?MINIO_ENDPOINT}
    accessKey = ${?MINIO_ACCESS_KEY}
    secretKey = ${?MINIO_SECRET_KEY}
    bucket = "athletica-crm"
    bucket = ${?MINIO_BUCKET}
}

smtp {
    host = "smtp.go1.unisender.ru"
    host = ${?SMTP_HOST}
    port = 587
    port = ${?SMTP_PORT}
    username = ${?SMTP_USERNAME}
    password = ${?SMTP_PASSWORD}
    fromAddress = "robot@tronline.ru"
    fromAddress = ${?SMTP_FROM_ADDRESS}
    fromName = "Тренерская online"
    fromName = ${?SMTP_FROM_NAME}
}
